//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAS_GO_CREDIT
    {
        public string MIN_NO { get; set; }
        public string GROUPNO_TX { get; set; }
        public string CCY_TX { get; set; }
        public Nullable<decimal> AMOUNT_AMT { get; set; }
        public string CUSTID_TX { get; set; }
        public string ACC_CD_TX { get; set; }
        public string ACCNUM_TX { get; set; }
        public string DETAILS_TX { get; set; }
        public string ADVISEPRINT_TX { get; set; }
        public string FXCCY_TX { get; set; }
        public Nullable<decimal> INTERRATE_INT { get; set; }
        public Nullable<decimal> EXCHRATE_INT { get; set; }
        public string ENTITY_TX { get; set; }
        public string DIVISION_TX { get; set; }
        public string TYPE_TX { get; set; }
        public string CHECKNO_TX { get; set; }
        public string FUND_TX { get; set; }
        public Nullable<System.DateTime> AVAILABLE_DATE { get; set; }
        public string IBF_TX { get; set; }
    }
}
