//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAN_MASTER_Permission
    {
        public int id { get; set; }
        public int DEPT_ID { get; set; }
        public string DEPARTMENT_CD { get; set; }
    }
}
